gtk+3: fix yocto-check-layer failure
Fix yocto-check-layer failure for gtk+3:

INFO: test_patches_upstream_status (common.CommonCheckLayer)
INFO:  ... expected failure
INFO: Traceback (most recent call last):
  File "/path_to/poky/scripts/lib/checklayer/cases/common.py", line 87, in test_patches_upstream_status
    self.assertEqual(len(patches), 0 , \
AssertionError: 1 != 0 : Found following patches with malformed or missing upstream status:
/path_to/meta-anaconda/recipes-gnome/gtk+/files/workaround-for-anaconda-installer-while-loading-libA.patch

Signed-off-by: Kai Kang <kai.kang@windriver.com>